spec:
  name: browser-base64-decoding
  region: nyc
  services:
  - name: web
    dockerfile_path: Dockerfile.digitalocean
    source_dir: /
    github:
      repo: TSstaticWebsites/base64-test
      branch: master
      deploy_on_push: true
    http_port: 80
    instance_count: 1
    instance_size_slug: basic-s
    routes:
    - path: /
    health_check:
      http_path: /