name: browser-base64-decoding
region: nyc
services:
- dockerfile_path: Dockerfile.digitalocean
  github:
    branch: master
    deploy_on_push: true
    repo: TSstaticWebsites/base64-test
  http_port: 80
  instance_count: 1
  instance_size_slug: basic-s
  name: web
  source_dir: /